### ISSUE TITLE
Music playback fails

### ISSUE THREAD

**Issue by sohamb117** [anirudhb/neeko-issues#3]
When using Youtube to search for songs, music playback fails on certain songs (unreliable and inconsistent, hard to reproduce).

**Comment by anirudhb** [comment]
Related to the youtube_dl error "Could not find a suitable source" -- currently we only look for audio so this may be problematic for videos that only have video and not audio by itself.

Will probably tackle it soon, this is P1.

**Comment by anirudhb** [comment]
Should be fixed with cookies.
